import java.util.Arrays;
import java.util.Comparator;

/**
 * Created by Jerry on 27-02-2017.
 */
public class RelativeSorting {
    public String[] findRelativeRanks(int[] nums) {

        //  Arrays.sort(nums,new Comparator<>());
        return null;

    }


    /**Given two strings s and t which consist of only lowercase letters.

     String t is generated by random shuffling string s and then add one more letter at a random position.

     Find the letter that was added in t.

     Example:

     Input:
     s = "abcd"
     t = "abcde"

     Output:
     e

     Explanation:
     'e' is the letter that was added.

     * https://leetcode.com/problems/find-the-difference/#/description
     * @param s
     * @param t
     * @return
     */

    public char findTheDifference(String s, String t) {
        int charCode = t.charAt(s.length());
        // Iterate through both strings and char codes
        for (int i = 0; i < s.length(); ++i) {
            charCode -= (int)s.charAt(i);
            charCode += (int)t.charAt(i);
        }
        return (char)charCode;
    }

    /**
     * Bit manipulation
     */

    public char findTheDifferenceWithBitManipulation(String s, String t) {
        int n = t.length();
        char c = t.charAt(n - 1);
        for (int i = 0; i < n - 1; ++i) {
            c ^= s.charAt(i);
            c ^= t.charAt(i);
        }
        return c;
    }

    public int[] constructRectangle(int area) {
int result[] = new int[2];

        for(int i =1;i*i<=area;i++){
            if(area%i==0){
                result[0] = (area/i);
                result[1] = i;


            }
        }
        return result;
    }

    public int[] constructRectangleOptimized(int area) {
        int x=1;
        for( int i =1;i*i<=area ;i++)
            if(area%i==0)
                x=i;

        return new int[]{area/x,x};
    }




}
